using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using ArcanumMessenger.Installer;

var version = typeof(Program).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
var devBuild = version == "0.0.0-dev";
// ARCANUM_TAG picks other images, e.g. ones built locally with docker-compose.build.yml
var imageTag = Environment.GetEnvironmentVariable("ARCANUM_TAG") is { Length: > 0 } tag ? tag : devBuild ? "latest" : version;
var command = args.Length > 0 ? args[0].ToLowerInvariant() : null;
var fromMenu = command == null;

if (OperatingSystem.IsWindows()) Console.OutputEncoding = Encoding.UTF8;

try
{
    command ??= Menu();
    return command switch
    {
        "install" => await Install(update: false),
        "update" => await Install(update: true),
        "start" => await Start(),
        "stop" => Stop(),
        "status" => Status(),
        "logs" => Logs(args.Skip(1).ToArray()),
        "uninstall" => await Uninstall(),
        "version" or "--version" or "-v" => Print(version),
        "exit" => 0,
        _ => Help(),
    };
}
catch (FatalException e)
{
    Ui.Fail(e.Message);
    return 1;
}
catch (OperationCanceledException)
{
    return 0;
}
catch (Exception e) when (e is NotSupportedException or InvalidOperationException && e.Message.Contains("interactive"))
{
    Ui.Fail("This needs an interactive terminal to ask its questions.");
    return 1;
}
finally
{
    // A double-clicked installer's window would close before anyone could read it
    if (OperatingSystem.IsWindows() && args.Length == 0)
    {
        Console.WriteLine();
        Console.Write("Press Enter to close...");
        Console.ReadLine();
    }
}

string Menu()
{
    Ui.Banner(devBuild ? "development build" : $"v{version}");
    if (!Stack.Installed) return Ui.Confirm("Install Arcanum on this computer?", true) ? "install" : "exit";

    var choice = Ui.Choose("What do you want to do?",
        "Update", "Status", "Start", "Stop", "Logs", "Uninstall", "Exit");
    return choice.ToLowerInvariant();
}

async Task<int> Install(bool update)
{
    var env = new EnvFile(Paths.Env);
    if (update && !env.Existed) throw Ui.Die($"Arcanum isn't installed in {Paths.Home} yet - run: {Self()} install");
    if (!fromMenu) Ui.Banner(env.Existed ? "Updating this installation" : "Installer");

    await Stack.CheckDocker();
    Directory.CreateDirectory(Paths.Home);
    Stack.WriteComposeFile(devBuild ? "(development build)" : $"v{version}", imageTag);
    await CheckOldData(env);
    Configure(env);
    var certChanged = await Certificates.Setup(env);

    Ui.Section("Download and start");
    if (!env.Existed) Ui.Note("The first download is several hundred MB.");
    if (Stack.Compose("up", "-d", "--remove-orphans", "--pull", imageTag == "latest" ? "always" : "missing") != 0)
        throw Ui.Die($"docker compose couldn't start Arcanum - see above. Fix it and run: {Self()} update");
    if (certChanged) await Stack.ComposeCapture("restart", "client");

    await WaitUntilHealthy();
    Summary(env);
    if (!env.Existed) OfferCommand();
    return 0;
}

// A new .env can't run on an old database: Postgres keeps the password it was created with,
// and data encrypted with the old keys stays unreadable with new ones.
async Task CheckOldData(EnvFile env)
{
    if (env.Existed || !await Stack.VolumeExists(Stack.DbVolume)) return;

    Ui.Section("Data from an earlier install");
    Ui.Warn("This machine still has the database of an earlier Arcanum install, but no .env for it.");
    Ui.Note("A new .env means new passwords and keys - that database won't accept them.");
    var choice = Ui.Choose("What should happen to the old data?",
        "Stop here - I'll put its .env back first",
        "Delete it and start fresh");
    if (choice.StartsWith("Stop"))
    {
        Ui.Note($"Put the old .env into {Paths.Home} and run {Self()} install again.");
        throw new OperationCanceledException();
    }

    if (!Ui.Confirm("This permanently deletes every account, message and file of that install. Delete?", false))
        throw new OperationCanceledException();
    await Ui.Spin("Removing the old containers and data...", () => Stack.ComposeCapture("down", "-v"));
    Ui.Ok("Old data removed");
}

void Configure(EnvFile env)
{
    Ui.Section("Configuration");
    if (env.Existed)
    {
        Ui.Ok($"Found {Paths.Env} - existing values stay as they are");
        try { Paths.MakePrivate(Paths.Env); } catch (UnauthorizedAccessException) { }
    }
    else
    {
        env.Create($"# Generated by the Arcanum installer on {DateTime.Now:yyyy-MM-dd}. Back it up - see \"Backups\" in the README.");
    }

    env.Default("POSTGRES_HOST", "db");
    env.Default("POSTGRES_DB", "arcanum");
    env.Default("POSTGRES_USER", "arcanum_user");
    env.Default("POSTGRES_PASSWORD", Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(24)));
    env.Default("MINIO_ROOT_USER", "arcanum");
    env.Default("MINIO_ROOT_PASSWORD", Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(24)));
    // The API reads these four as base64
    env.Default("ENCRYPTION_KEK", Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)));
    env.Default("EMAIL_HASH_PEPPER", Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)));
    env.Default("PUBLIC_ID_HASH_PEPPER", Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)));
    env.Default("JWT_SECRET", Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)));
    Ui.Ok("Secrets and service passwords are in place");

    if (env["SMTP_HOST"] == null) AskSmtp(env);

    var placeholders = env.All
        .Where(pair => Regex.IsMatch(pair.Value, "your_|example\\.com|<username>"))
        .Select(pair => pair.Key)
        .ToList();
    if (placeholders.Count > 0)
    {
        Ui.Warn($"{Paths.Env} still has example values in: {string.Join(", ", placeholders)}");
        if (!Ui.Confirm("Continue anyway?", false)) throw new OperationCanceledException();
    }
}

void AskSmtp(EnvFile env)
{
    Ui.Note("Arcanum emails a one-time code at sign-up and account recovery, so it needs a mailbox to send from.");
    var provider = Ui.Choose("Mail provider", "Gmail", "Outlook.com", "Yahoo", "Something else");
    var (host, port) = provider switch
    {
        "Gmail" => ("smtp.gmail.com", "587"),
        "Outlook.com" => ("smtp-mail.outlook.com", "587"),
        "Yahoo" => ("smtp.mail.yahoo.com", "587"),
        _ => (Ui.Ask("SMTP server:"), Ui.Ask("SMTP port:", "587")),
    };
    var user = Ui.Ask("Mailbox address:");
    Ui.Note("Most providers want an app password here, not your normal one (Gmail: Google Account -> Security -> App passwords).");
    var password = Ui.Ask($"Password for {user}:", secret: true);

    env.Add("SMTP_HOST", host);
    env.Add("SMTP_PORT", port);
    env.Add("SMTP_USERNAME", user);
    env.Add("SMTP_PASSWORD", password);
    Ui.Ok($"Mail goes out through {host} as {user}");
}

async Task WaitUntilHealthy()
{
    var problem = await Ui.Spin("Waiting for Arcanum to come up - the first start also sets up the database...", Stack.WaitUntilHealthy);
    if (problem is null)
    {
        Ui.Ok("Everything is up and healthy");
        return;
    }

    var (service, failing) = problem.Value;
    var name = service == "api" ? "The API" : "nginx (the client container)";
    Ui.Warn(failing
        ? $"{name} keeps failing to start. Its last log lines:"
        : $"Arcanum didn't come up within 5 minutes - {name} is still not ready. Its last log lines:");
    Stack.Compose("logs", "--tail", "30", service);
    if (service == "client" && (await Stack.ComposeCapture("logs", "client")).Out.Contains("cannot load certificate"))
        Ui.Note($"nginx can't read the certificate in {Certificates.CertsDir(new EnvFile(Paths.Env))}.");
    if (service == "api" && (await Stack.ComposeCapture("logs", "api")).Out.Contains("28P01"))
    {
        Ui.Warn($"The database was created with a different POSTGRES_PASSWORD than the one in {Paths.Env}.");
        Ui.Note($"Put back the .env it was created with - or, to start over, run {Self()} uninstall and delete everything.");
    }
    throw Ui.Die($"Fix what's above and run {Self()} update. Full logs: {Self()} logs");
}

void Summary(EnvFile env)
{
    var addresses = Certificates.PublicAddresses(env);
    if (addresses.Count == 0) addresses.Add("localhost");

    var lines = new List<string> { Ui.Bold("Arcanum is running", Ui.GreenColour), "", "Open it at:" };
    lines.AddRange(addresses.Select(a => Ui.Plain($"  https://{a}/")));
    if (Certificates.IssuedByOwnCa(env))
    {
        lines.Add("");
        lines.Add(Ui.Plain("Other devices warn about the certificate until they trust"));
        lines.Add(Ui.Plain($"{Paths.CaCert} - see \"Trusting the certificate\" in the README."));
    }
    else if (Certificates.IsSelfSigned(env))
    {
        lines.Add("");
        lines.Add(Ui.Plain("Browsers will warn about the self-signed certificate - that's expected."));
    }
    lines.Add("");
    lines.Add(Ui.Bold($"Back up {Paths.Env} somewhere safe.", Ui.YellowColour));
    lines.Add(Ui.Plain("Lose its keys and existing accounts can't sign in again."));
    lines.Add("");
    lines.Add(Ui.Dim($"Update:  {Self()} update"));
    lines.Add(Ui.Dim($"Logs:    {Self()} logs"));
    lines.Add(Ui.Dim($"Stop:    {Self()} stop"));
    Console.WriteLine();
    Ui.Box(lines);
}

async Task<int> Start()
{
    RequireInstall();
    if (Stack.Compose("up", "-d") != 0) throw Ui.Die("docker compose couldn't start Arcanum - see above.");
    await WaitUntilHealthy();
    return Status();
}

int Stop()
{
    RequireInstall();
    return Stack.Compose("stop");
}

int Status()
{
    RequireInstall();
    Stack.Compose("ps");
    var env = new EnvFile(Paths.Env);
    Console.WriteLine();
    foreach (var address in Certificates.PublicAddresses(env)) Ui.Note($"https://{address}/");
    return 0;
}

int Logs(string[] services)
{
    RequireInstall();
    return Stack.Compose(["logs", "-f", "--tail", "100", .. services]);
}

async Task<int> Uninstall()
{
    if (!fromMenu) Ui.Banner("Uninstall");
    if (!Directory.Exists(Paths.Home))
    {
        Ui.Ok("Arcanum isn't installed here - nothing to remove.");
        return 0;
    }
    // Even without a .env, the compose file can still take down what an earlier install left
    var hasCompose = File.Exists(Paths.Compose);

    var choice = Ui.Choose("What should go?",
        "Only the containers - keep the data, settings and certificate",
        "Everything - every account, message and file, the settings and the certificate",
        "Nothing, cancel");
    if (choice.StartsWith("Nothing")) return 0;

    if (choice.StartsWith("Only"))
    {
        if (hasCompose) Stack.Compose("down");
        Ui.Ok($"Containers removed. Everything else is still in {Paths.Home} - {Self()} install brings it back.");
        return 0;
    }

    if (!Ui.Confirm("This permanently deletes every account, message and file. Delete?", false)) return 0;
    if (hasCompose)
    {
        var images = await Stack.OwnImages();
        await Ui.Spin("Removing the containers and data...", () => Stack.ComposeCapture("down", "-v", "--remove-orphans"));
        foreach (var image in images) await Shell.Capture("docker", "image", "rm", image);
    }
    using (var ca = Certificates.LoadCa())
    {
        if (ca != null) await Trust.Remove(ca);
    }
    Directory.Delete(Paths.Home, true);
    Ui.Ok("Arcanum and all its data are gone");

    if (!OperatingSystem.IsWindows() && File.Exists(InstalledCommand) && Ui.Confirm($"Remove the arcanum command from {InstalledCommand} too?", true))
        Shell.RunAsRoot("rm", "-f", InstalledCommand);
    return 0;
}

// Copies this binary into /usr/local/bin, so `arcanum` works from anywhere.
void OfferCommand()
{
    var self = Environment.ProcessPath;
    if (OperatingSystem.IsWindows() || !SingleFile || self == null || InPath(self)) return;

    Console.WriteLine();
    if (!Ui.Confirm($"Install the arcanum command into {Path.GetDirectoryName(InstalledCommand)}, so it runs from any folder?", true)) return;
    Shell.RunAsRoot("mkdir", "-p", Path.GetDirectoryName(InstalledCommand)!);
    if (Shell.RunAsRoot("install", "-m", "755", self, InstalledCommand) == 0) Ui.Ok("From now on it's just: arcanum update, arcanum logs, ...");
    else Ui.Warn($"Couldn't copy it - keep running it as {Self()}");
}

void RequireInstall()
{
    if (!Stack.Installed) throw Ui.Die($"Arcanum isn't installed in {Paths.Home} yet - run: {Self()} install");
}

// How to run this binary again from where the user is
string Self()
{
    var self = Environment.ProcessPath;
    if (self == null || !SingleFile) return "arcanum";
    if (InPath(self)) return Path.GetFileNameWithoutExtension(self);
    var relative = Path.GetRelativePath(Environment.CurrentDirectory, self);
    if (relative.StartsWith("..")) return self;
    if (relative.Contains(Path.DirectorySeparatorChar)) return relative;
    return (OperatingSystem.IsWindows() ? ".\\" : "./") + relative;
}

bool InPath(string file) =>
    (Environment.GetEnvironmentVariable("PATH") ?? "").Split(Path.PathSeparator)
    .Any(dir => dir.Length > 0 && Path.GetFullPath(dir) == Path.GetDirectoryName(file));

int Print(string text)
{
    Console.WriteLine(text);
    return 0;
}

int Help()
{
    Ui.Banner(devBuild ? "development build" : $"v{version}");
    Ui.Box([
        Ui.Plain($"Usage: {Self()} <command>"),
        "",
        Ui.Plain("install     set up Arcanum on this computer"),
        Ui.Plain("update      get the images this version ships and restart"),
        Ui.Plain("start       start it"),
        Ui.Plain("stop        stop it"),
        Ui.Plain("status      show the containers and the addresses"),
        Ui.Plain("logs [api]  follow the logs, of everything or one service"),
        Ui.Plain("uninstall   remove the containers, or everything"),
        "",
        Ui.Dim($"Everything lives in {Paths.Home}"),
    ]);
    return command is null or "help" or "--help" or "-h" ? 0 : 1;
}

partial class Program
{
    const string InstalledCommand = "/usr/local/bin/arcanum";

    // false under `dotnet run`, where the binary can't be copied anywhere on its own
#pragma warning disable IL3000 // the empty Location of a single-file app is exactly what's checked
    static bool SingleFile => string.IsNullOrEmpty(typeof(Program).Assembly.Location);
#pragma warning restore IL3000
}
